In [2]:
import torch
import torchvision
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt

## The Pytorch Tensor

In [3]:
W = [[1, 1, 1], [1.5, 1.5, 1.5], [2, 2, 2]]  # 3 * 3

x = [[6], [7], [8]]  # 3*1
b = [[1], [1], [1]]  # 3*1

# Varaible to store output
y = [[0], [0], [0]]

In [10]:
# We can transfrom our list of list intoa `numpy array` by using the function `array`
W_np = np.array(W)

x_np = np.array(x)

# Lets use the function "ones" to create an array of ones!
b_np = np.ones((3,1))

# Lets now compute Wx +b using theses numpy variables! - Matrix Multiplication
output = np.matmul(W_np, x_np) + b_np

# Print out the result
print(f"Output: {output}\n")
print(f"Output shape: {output.shape} \n")


Output: [[22. ]
 [32.5]
 [43. ]]

Output shape: (3, 1) 



Now in Pytorch!

In [11]:
W_torch = torch.FloatTensor(W)

x_troch = torch.FloatTensor(x)

# let use the function `ones` to create an array of ones!
b_torch = torch.ones(3, 1)

# Lets npw compute Wx + b using these numpy variables!
output = torch.matmul(W_torch, x_troch) + b_torch

# Print out the result
print(f"output: {output}\noutput shape: {output.shape}\n")

output: tensor([[22.0000],
        [32.5000],
        [43.0000]])
output shape: torch.Size([3, 1])



There are more function in pytorch to transfer pytorch tensor to numpy arrays and back

In [12]:
# Create a random Numpy arrays
np_array = np.random.random((3, 4))
print(f"Numpy array: {np_array}\n")

# Convert to pytorch tensor
torch_tensor = torch.FloatTensor(np_array)
print(f"Pytorch tensor: {torch_tensor}")

# Convert back to a Numpy array
np_array2 = torch_tensor.numpy()
print(f"Numpy array: {np_array2}")

Numpy array: [[0.98674075 0.25585276 0.29858554 0.10184861]
 [0.54812487 0.18615461 0.22937106 0.31687187]
 [0.13590942 0.76843451 0.24151383 0.99715721]]

Pytorch tensor: tensor([[0.9867, 0.2559, 0.2986, 0.1018],
        [0.5481, 0.1862, 0.2294, 0.3169],
        [0.1359, 0.7684, 0.2415, 0.9972]])
Numpy array: [[0.98674077 0.25585276 0.29858553 0.1018486 ]
 [0.54812485 0.1861546  0.22937106 0.31687188]
 [0.13590942 0.7684345  0.24151383 0.9971572 ]]


## On to Pytorch !

Let futher explore Pytorch and its simiarities to Numpy and then see what new functionalities it bring to the table!!

### Basic Element-wise Operations
Let's quickly go back over some basics using Pytorch

In [43]:
# Lets create a 2D Tensor using torch.rand
y = torch.rand(4, 5)
print(f"1D tensor: \n{y}")

# Lets perform normal python scalar arithmetic on Torch tensor
print(f"Scalar Multiplication:\n {y *10}")
print(f"Addition and square: \n {(y+1)**2}")
print(f"Addition: \n{y+y}")
print(f"Addition and division:\n {y / (y+1)}")

# We can use a combination of torch functions and normalpython arithmetic
print(f"Power and suare root: \n {torch.sqrt(y**2)}")

# Torch tensors are objects and have functions
print(f"\nY :{y}\nMin: {y.min():.2f}\nMax: {y.max():.2f}\nStd: {y.std()}\nSum: {y.sum():.3f}")

1D tensor: 
tensor([[0.6744, 0.3185, 0.8346, 0.4667, 0.4758],
        [0.2989, 0.5851, 0.1845, 0.7865, 0.7065],
        [0.3288, 0.2283, 0.5137, 0.8828, 0.1646],
        [0.6955, 0.4893, 0.1674, 0.2161, 0.9657]])
Scalar Multiplication:
 tensor([[6.7442, 3.1850, 8.3462, 4.6668, 4.7578],
        [2.9888, 5.8509, 1.8451, 7.8646, 7.0651],
        [3.2877, 2.2833, 5.1367, 8.8280, 1.6464],
        [6.9553, 4.8925, 1.6742, 2.1605, 9.6575]])
Addition and square: 
 tensor([[2.8037, 1.7384, 3.3658, 2.1511, 2.1779],
        [1.6871, 2.5125, 1.4031, 3.1914, 2.9122],
        [1.7656, 1.5088, 2.2912, 3.5449, 1.3564],
        [2.8748, 2.2179, 1.3629, 1.4788, 3.8642]])
Addition: 
tensor([[1.3488, 0.6370, 1.6692, 0.9334, 0.9516],
        [0.5978, 1.1702, 0.3690, 1.5729, 1.4130],
        [0.6575, 0.4567, 1.0273, 1.7656, 0.3293],
        [1.3911, 0.9785, 0.3348, 0.4321, 1.9315]])
Addition and division:
 tensor([[0.4028, 0.2416, 0.4549, 0.3182, 0.3224],
        [0.2301, 0.3691, 0.1558, 0.4402, 0.4140],
  

### Tensor Operations

In [48]:
# Create two 3D Tensors
tensor_1 = torch.rand(3,3,3)
tensor_2 = torch.rand(3,3,3)
 
# Add the 2 Tensors
print(f"Add tensor:\n {tensor_1 + tensor_2}")

# We can'tperform a normal matrix multiplocation on a 3d tensor
# But we can treat the 3D tensor as batch (like a stack) of 2D tensors
# And performnormal matrix multiplication indepedantly on each pair of 2D matricies
print(f"Batch Multiplication:\n {torch.bmm(tensor_1, tensor_2)}")

Add tensor:
 tensor([[[0.2983, 1.6726, 0.4420],
         [0.9052, 0.1658, 0.5641],
         [0.9990, 0.9015, 0.8909]],

        [[0.7775, 0.2540, 1.1831],
         [1.7821, 0.7533, 1.0743],
         [1.4934, 1.6080, 0.9827]],

        [[1.1716, 0.9154, 0.3596],
         [0.6050, 0.4805, 0.6613],
         [0.2688, 0.4573, 0.2039]]])
Batch Multiplication:
 tensor([[[0.8207, 0.2832, 0.5959],
         [0.1785, 0.2263, 0.1583],
         [0.6426, 0.3389, 0.3154]],

        [[0.6780, 0.6840, 0.9047],
         [1.2337, 0.9146, 1.3204],
         [1.1098, 0.2857, 0.6601]],

        [[0.7163, 0.2863, 0.4116],
         [0.2551, 0.0951, 0.1314],
         [0.2655, 0.0989, 0.1446]]])


In [51]:
# Lets create a moreinteresting tensor
tensor_3 = torch.rand(2,4,5)
# We can swapthe Tensor dimensions
print(f"Tensor 3:\n {tensor_3}\nTensor shape: {tensor_3.shape}")

# Tranpose will swpathe dimension it is given
print(f"Swap:\n{tensor_3.transpose(0,2)}\nTensor shape: {tensor_3.transpose(0,2).shape}")

Tensor 3:
 tensor([[[0.2198, 0.0338, 0.7519, 0.9452, 0.1264],
         [0.8126, 0.5071, 0.2424, 0.5215, 0.0250],
         [0.9803, 0.1088, 0.1661, 0.2209, 0.1197],
         [0.4625, 0.8054, 0.3131, 0.8079, 0.0571]],

        [[0.8741, 0.2483, 0.7708, 0.4332, 0.9638],
         [0.6537, 0.3252, 0.8817, 0.9697, 0.5643],
         [0.8247, 0.4977, 0.4986, 0.7110, 0.5692],
         [0.0720, 0.7256, 0.8623, 0.4897, 0.3186]]])
Tensor shape: torch.Size([2, 4, 5])
Swap:
tensor([[[0.2198, 0.8741],
         [0.8126, 0.6537],
         [0.9803, 0.8247],
         [0.4625, 0.0720]],

        [[0.0338, 0.2483],
         [0.5071, 0.3252],
         [0.1088, 0.4977],
         [0.8054, 0.7256]],

        [[0.7519, 0.7708],
         [0.2424, 0.8817],
         [0.1661, 0.4986],
         [0.3131, 0.8623]],

        [[0.9452, 0.4332],
         [0.5215, 0.9697],
         [0.2209, 0.7110],
         [0.8079, 0.4897]],

        [[0.1264, 0.9638],
         [0.0250, 0.5643],
         [0.1197, 0.5692],
         [0.05

### Indexing

In [67]:
# Create a 4D Tensor
tensor = torch.rand( 2,3,1,4)
print(f"Input tensor:\n{tensor}")

Input tensor:
tensor([[[[0.3936, 0.6159, 0.6997, 0.0966]],

         [[0.4806, 0.0271, 0.4104, 0.0383]],

         [[0.5541, 0.3746, 0.7969, 0.7920]]],


        [[[0.2897, 0.3034, 0.9928, 0.5285]],

         [[0.9240, 0.9457, 0.9256, 0.2280]],

         [[0.2925, 0.7888, 0.4822, 0.1003]]]])


In [79]:
tensor[:,1]

tensor([[[0.4806, 0.0271, 0.4104, 0.0383]],

        [[0.9240, 0.9457, 0.9256, 0.2280]]])

In [ ]:
torch.from_numpy()